version: '2'
services:
        consul:
                image: "gliderlabs/consul-server"
                container_name: "consul"
                command: ['-bootstrap', '-advertise=$HOST_IP']
                network_mode: "host"

        registrator:
                image: "gliderlabs/registrator"
                container_name: "registrator"
                network_mode: "host"
                command: ['consul://$HOST_IP:8500']
                depends_on:
                        - consul
                volumes:
                        - /var/run/docker.sock:/tmp/docker.sock

        reloadable_nginx:
                build: ./reloadable-nginx
                depends_on:
                       - registrator
                network_mode: "host"
                container_name: reloadable_nginx
                ports:
                        - 80:80
