version: '2'
services:
        consul:
                image: "consul"
                container_name: "consul"
                command: ['-bootstrap', '-advertise=127.0.0.1']
                network_mode: "host"

        registrator:
                image: "gliderlabs/registrator"
                container_name: "registrator"
                network_mode: "host"
                command: ['consul://127.0.0.1:8500']
                depends_on:
                        - consul
                volumes:
                        - /var/run/docker.sock:/tmp/docker.sock

        reloadable_nginx:
                build: ./reloadable-nginx
                depends_on:
                       - registrator
                network_mode: "host"
                container_name: reloadable_nginx
                ports:
                        - 80:80
